# Generated by Django 5.1.7 on 2025-03-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_ayuda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(default='Disponible'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('P', 'publicitario'), ('T', 'Tecnologico')], default='', max_length=1),
        ),
    ]
