# Generated by Django 5.1.7 on 2025-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_ayuda', '0002_servicio_descripcion_servicio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.CharField(default=200, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('P', 'PUBLICITARIO'), ('T', 'TECNOLOGICO')], default='P', max_length=1),
        ),
    ]
