# Generated by Django 5.1.7 on 2025-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_ayuda', '0003_alter_servicio_precio_alter_servicio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('P', 'PUBLICITARIO'), ('T', 'TECNOLOGICO')], default='T', max_length=1),
        ),
    ]
