# Generated by Django 5.1.7 on 2025-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_ayuda', '0005_alter_servicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.CharField(default='', max_length=200),
        ),
    ]
